test_that("whichDir(matrix)", {
  m <- matrix(1:12, nrow=4)

  expect_equal(whichDir(6, 1, m), 1)
  expect_equal(whichDir(6, 5, m), 2)
  expect_equal(whichDir(6, 10, m), 3)
  expect_equal(whichDir(6, 7, m), 4)
  expect_equal(whichDir(6, 3, m), 5)
  expect_equal(whichDir(6, 2, m), 6)
  expect_equal(whichDir(6, 4, m), NA)
  expect_equal(whichDir(6, 9, m), NA)
  expect_equal(whichDir(6, 11, m), NA)
  expect_equal(whichDir(6, 12, m), NA)
  expect_equal(whichDir(6, 13, m), NA)
})


test_that("whichDir(array)", {
  m <- array(1:24, dim=c(4, 3, 2))

  expect_equal(whichDir(6, 1, m), 1)
  expect_equal(whichDir(6, 5, m), 2)
  expect_equal(whichDir(6, 10, m), 3)
  expect_equal(whichDir(6, 7, m), 4)
  expect_equal(whichDir(6, 3, m), 5)
  expect_equal(whichDir(6, 2, m), 6)
  expect_equal(whichDir(6, 4, m), NA)
  expect_equal(whichDir(6, 9, m), NA)
  expect_equal(whichDir(6, 11, m), NA)
  expect_equal(whichDir(6, 12, m), NA)
  expect_equal(whichDir(6, 13, m), NA)
  expect_equal(whichDir(6, 14, m), NA)
  expect_equal(whichDir(6, 15, m), NA)
  expect_equal(whichDir(6, 16, m), NA)
  expect_equal(whichDir(6, 17, m), NA)
  expect_equal(whichDir(6, 18, m), NA)
  expect_equal(whichDir(6, 19, m), NA)
  expect_equal(whichDir(6, 20, m), NA)
  expect_equal(whichDir(6, 21, m), NA)
  expect_equal(whichDir(6, 22, m), NA)
  expect_equal(whichDir(6, 23, m), NA)
  expect_equal(whichDir(6, 24, m), NA)
  expect_equal(whichDir(6, 25, m), NA)

  expect_equal(whichDir(18, 1+12, m), 1)
  expect_equal(whichDir(18, 5+12, m), 2)
  expect_equal(whichDir(18, 10+12, m), 3)
  expect_equal(whichDir(18, 7+12, m), 4)
  expect_equal(whichDir(18, 3+12, m), 5)
  expect_equal(whichDir(18, 2+12, m), 6)
  expect_equal(whichDir(18, 4+12, m), NA)
  expect_equal(whichDir(18, 9+12, m), NA)
  expect_equal(whichDir(18, 11+12, m), NA)
  expect_equal(whichDir(18, 12+12, m), NA)
  expect_equal(whichDir(18, 1, m), NA)
  expect_equal(whichDir(18, 2, m), NA)
  expect_equal(whichDir(18, 3, m), NA)
  expect_equal(whichDir(18, 4, m), NA)
  expect_equal(whichDir(18, 5, m), NA)
  expect_equal(whichDir(18, 6, m), NA)
  expect_equal(whichDir(18, 7, m), NA)
  expect_equal(whichDir(18, 8, m), NA)
  expect_equal(whichDir(18, 9, m), NA)
  expect_equal(whichDir(18, 10, m), NA)
  expect_equal(whichDir(18, 11, m), NA)
  expect_equal(whichDir(18, 12, m), NA)
})
