// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// reachability
List reachability(const NumericMatrix m, const NumericVector dist);
RcppExport SEXP _hexmatrix_reachability(SEXP mSEXP, SEXP distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type dist(distSEXP);
    rcpp_result_gen = Rcpp::wrap(reachability(m, dist));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hexmatrix_reachability", (DL_FUNC) &_hexmatrix_reachability, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_hexmatrix(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
