// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// whichDir
int whichDir(int cur, int other, int rows, int cols);
RcppExport SEXP _hexmatrix_whichDir(SEXP curSEXP, SEXP otherSEXP, SEXP rowsSEXP, SEXP colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type cur(curSEXP);
    Rcpp::traits::input_parameter< int >::type other(otherSEXP);
    Rcpp::traits::input_parameter< int >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< int >::type cols(colsSEXP);
    rcpp_result_gen = Rcpp::wrap(whichDir(cur, other, rows, cols));
    return rcpp_result_gen;
END_RCPP
}
// path
NumericVector path(int to, NumericMatrix paths);
RcppExport SEXP _hexmatrix_path(SEXP toSEXP, SEXP pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type paths(pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(path(to, paths));
    return rcpp_result_gen;
END_RCPP
}
// pathReduce
List pathReduce(const List data, const NumericMatrix path, const RObject origin, const Function f);
RcppExport SEXP _hexmatrix_pathReduce(SEXP dataSEXP, SEXP pathSEXP, SEXP originSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type path(pathSEXP);
    Rcpp::traits::input_parameter< const RObject >::type origin(originSEXP);
    Rcpp::traits::input_parameter< const Function >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(pathReduce(data, path, origin, f));
    return rcpp_result_gen;
END_RCPP
}
// reachability
List reachability(const NumericMatrix m, const NumericVector dist, int target);
RcppExport SEXP _hexmatrix_reachability(SEXP mSEXP, SEXP distSEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type dist(distSEXP);
    Rcpp::traits::input_parameter< int >::type target(targetSEXP);
    rcpp_result_gen = Rcpp::wrap(reachability(m, dist, target));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hexmatrix_whichDir", (DL_FUNC) &_hexmatrix_whichDir, 4},
    {"_hexmatrix_path", (DL_FUNC) &_hexmatrix_path, 2},
    {"_hexmatrix_pathReduce", (DL_FUNC) &_hexmatrix_pathReduce, 4},
    {"_hexmatrix_reachability", (DL_FUNC) &_hexmatrix_reachability, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_hexmatrix(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
