# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.altpaths <- function(source, target, dist, regions, n, step, f) {
    .Call(`_hexmatrix_altpaths`, source, target, dist, regions, n, step, f)
}

.whichDir <- function(cur, other, rows, cols) {
    .Call(`_hexmatrix_whichDir`, cur, other, rows, cols)
}

.path <- function(to, paths) {
    .Call(`_hexmatrix_path`, to, paths)
}

.pathReduce <- function(data, path, origin, f) {
    .Call(`_hexmatrix_pathReduce`, data, path, origin, f)
}

.reachability <- function(m, dist, trans, target) {
    .Call(`_hexmatrix_reachability`, m, dist, trans, target)
}

.shortest <- function(source, target, dist) {
    .Call(`_hexmatrix_shortest`, source, target, dist)
}

.region <- function(m, index) {
    .Call(`_hexmatrix_region`, m, index)
}

.shiftDown <- function(v, rows) {
    .Call(`_hexmatrix_shiftDown`, v, rows)
}

.shiftUp <- function(v, rows) {
    .Call(`_hexmatrix_shiftUp`, v, rows)
}

.shiftRight <- function(v, rows, cols, odd) {
    .Call(`_hexmatrix_shiftRight`, v, rows, cols, odd)
}

.shiftLeft <- function(v, rows, cols, odd) {
    .Call(`_hexmatrix_shiftLeft`, v, rows, cols, odd)
}

